const AGENCIES={malacatan:{name:"Malacatán",phone:"50236500543"},sanpablo:{name:"San Pablo",phone:"50259173974"}};
const EXT=["webp","jpg","jpeg","png","gif","avif","svg"];
const $=s=>document.querySelector(s);
const grid=$("#catalogGrid"),desktopFilters=$("#desktopFilters"),mobileFilters=$("#mobileFilters"),searchInput=$("#searchInput"),sortSelect=$("#sortSelect");
const productModal=$("#productModal"),agencyModal=$("#agencyModal"),aboutModal=$("#aboutModal"),agencyText=$("#agencyText");
let activeCategory="Todas",selectedProduct=null;
const money=v=>`Q${Number(v).toLocaleString("es-GT")}`;
const products=()=>CATEGORIES.flatMap(c=>c.products.map(p=>({...p,category:c.name})));
function tryImage(img,base,i=0){if(i>=EXT.length){img.style.display="none";return}img.src=`assets/img/motos/${base}.${EXT[i]}`;img.onerror=()=>tryImage(img,base,i+1)}
function image(base,alt){const img=document.createElement("img");img.alt=alt;img.loading="lazy";tryImage(img,base);return img}
function message(product,agency){return product?`Hola, vengo del catálogo web. Me interesa la moto ${product.shortName} (${product.model}) con precio de contado ${money(product.cash)}. Deseo más información en agencia ${agency}.`:`Hola, vengo del catálogo web. Deseo comunicarme con agencia ${agency}.`}
function show(m){m.classList.add("show");m.setAttribute("aria-hidden","false")}function hide(m){m.classList.remove("show");m.setAttribute("aria-hidden","true")}
function openAgency(product=null){selectedProduct=product;agencyText.textContent=product?`Elige la agencia para consultar por ${product.shortName}.`:"Selecciona una agencia y te llevaremos a WhatsApp.";show(agencyModal)}
function openProduct(product){selectedProduct=product;$("#detailImage").innerHTML=`<div class="placeholder">${product.shortName}</div>`;$("#detailImage").prepend(image(product.imageBase,product.model));$("#detailCategory").textContent=product.category;$("#detailName").textContent=product.shortName;$("#detailModel").textContent=product.model;$("#detailPrice").textContent=money(product.cash);$("#detailSku").textContent=`SKU: ${product.sku}`;$("#detailCode").textContent=`Código: ${product.code}`;show(productModal)}
function card(product,index){const el=document.createElement("article");el.className="card glass";el.style.animationDelay=`${Math.min(index*.035,.55)}s`;el.tabIndex=0;el.innerHTML=`<div class="image-wrap"><span class="category-pill">${product.category}</span><div class="placeholder">${product.shortName}</div></div><div class="card-body"><h3>${product.shortName}</h3><p class="model">${product.model}</p><div class="cash-price">${money(product.cash)}</div><button class="interest-btn" type="button">Me interesa esto</button></div>`;el.querySelector(".image-wrap").prepend(image(product.imageBase,product.model));el.addEventListener("click",()=>openProduct(product));el.addEventListener("keydown",e=>{if(e.key==="Enter")openProduct(product)});el.querySelector(".interest-btn").addEventListener("click",e=>{e.stopPropagation();openAgency(product)});return el}
function filterButton(name,count){return `<button class="filter ${activeCategory===name?"active":""}" data-category="${name}" type="button"><span class="ico">🏍</span><b>${name}</b><em>${count}</em></button>`}
function renderFilters(){const total=products().length;let html=filterButton("Todas",total);CATEGORIES.forEach(c=>html+=filterButton(c.name,c.products.length));desktopFilters.innerHTML=html;mobileFilters.innerHTML=html}
function filtered(){const q=searchInput.value.trim().toLowerCase();let list=products().filter(p=>(activeCategory==="Todas"||p.category===activeCategory)&&`${p.category} ${p.model} ${p.shortName} ${p.sku} ${p.code}`.toLowerCase().includes(q));if(sortSelect.value==="price-asc")list.sort((a,b)=>a.cash-b.cash);if(sortSelect.value==="price-desc")list.sort((a,b)=>b.cash-a.cash);if(sortSelect.value==="name-asc")list.sort((a,b)=>a.shortName.localeCompare(b.shortName,"es"));return list}
function render(){renderFilters();const list=filtered();grid.innerHTML="";if(!list.length){grid.innerHTML='<div class="empty glass">No se encontraron motos.</div>';return}list.forEach((p,i)=>grid.appendChild(card(p,i)))}
document.addEventListener("click",e=>{const f=e.target.closest(".filter");if(f){activeCategory=f.dataset.category;render()}});
searchInput.addEventListener("input",render);sortSelect.addEventListener("change",render);$("#openContact").addEventListener("click",()=>openAgency(null));$("#openAbout").addEventListener("click",()=>show(aboutModal));$("#closeProduct").addEventListener("click",()=>hide(productModal));$("#closeAgency").addEventListener("click",()=>hide(agencyModal));$("#closeAbout").addEventListener("click",()=>hide(aboutModal));$("#detailInterest").addEventListener("click",()=>{hide(productModal);openAgency(selectedProduct)});document.querySelectorAll(".agency").forEach(btn=>btn.addEventListener("click",()=>{const a=AGENCIES[btn.dataset.agency];window.open(`https://wa.me/${a.phone}?text=${encodeURIComponent(message(selectedProduct,a.name))}`,"_blank","noopener")}));[productModal,agencyModal,aboutModal].forEach(m=>m.addEventListener("click",e=>{if(e.target===m)hide(m)}));document.addEventListener("keydown",e=>{if(e.key==="Escape"){hide(productModal);hide(agencyModal);hide(aboutModal)}});
render();
